[project]
name = "koreader-sync-api"
version = "0.0.1"
description = "Quick and dirty implementation of the KOReader sync service"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.2",
]
